package main

// - `package main` declares this file belongs to the `main` package - required for any Go program that's meant to be run directly (not imported as a library).
// - `import` brings in two standard library packages:
//     - `net/http` gives you everything for building an HTTP server (ServeMux, Server, FileServer, etc.)
//     - `log` gives you tools for printing log messages, optionally with a fatal exit.
import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"sync/atomic"
	"time"

	"github.com/Nims001/chirpy/internal/auth"

	"github.com/google/uuid"

	"database/sql"
	"os"

	"github.com/Nims001/chirpy/internal/database"
	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
)

type apiConfig struct {
	fileserverHits  atomic.Int32
	databasequeries *database.Queries
	platform        string
}

type Chirp struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Body      string    `json:"body"`
	User_ID   uuid.UUID `json:"user_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
}

func main() {
	// loading environment variables from .env file
	godotenv.Load()

	dbURL := os.Getenv("DB_URL")
	platform := os.Getenv("PLATFORM")

	// connecting to the database using the connection string from the environment variable `DB_URL`.
	// The `sql.Open` function returns a database handle and an error. If there's an error opening the database, it logs the error and exits the program.
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalf("Error opening database: %v", err)
	}

	// This creates a new `database.Queries` struct, which is generated by sqlc and contains methods for interacting with the database (like `CreateUser`, `ResetUsers`, etc.).
	dbQueries := database.New(db)

	// This creates a new **ServeMux** - your router. Right now it's empty; no paths are registered yet. `:=` declares and assigns in one step (shorthand for `var sermux = ...`).
	sermux := http.NewServeMux()

	// 	This creates an `http.Server` struct:

	// - `Addr: ":8080"` tells it to listen on port 8080 on all network interfaces.
	// - `Handler: sermux` tells the server "whenever a request comes in, hand it off to `sermux` to figure out what to do."
	// - The `&` means you're taking a **pointer** to this struct - `s` holds the memory address of the server, not a copy of it. This matters because things like `ListenAndServe` need to be called on the actual server, not some duplicate copy.
	s := &http.Server{
		Addr:    ":8080",
		Handler: sermux,
	}

	// This creates an `apiConfig` struct that holds the database queries and platform information.
	// This struct is used to pass around configuration and shared state (like the request counter) to the various handler functions.
	apiCfg := &apiConfig{databasequeries: dbQueries, platform: platform}

	// This line registers a new route with the ServeMux:
	// 	Notice: at this point, `sermux` has no routes yet, but that's fine because Go doesn't execute this code top-to-bottom in the sense of "checking" anything - it's just building objects in memory.

	// ```go
	// 	sermux.Handle("/app/",http.FileServer(http.Dir("./")))
	// ```

	// Breaking this down from the inside out:

	// - `http.Dir("./")` - treats the current directory as the root folder to serve files from.
	// - `http.FileServer(...)` - creates a handler that knows how to serve files/directories as HTTP responses (handling things like content-type detection, directory listings, etc.).
	// - `sermux.Handle("/app/", ...)` - registers that fileserver handler on the mux, so that any request path starting with `/app/` gets routed to it.

	sermux.Handle("/app/", apiCfg.middlewareMetricsInc(http.StripPrefix("/app", http.FileServer(http.Dir("./")))))
	// we added the `http.StripPrefix` function to remove the `/app` prefix from the request path before passing it to the file server. This is necessary because the
	// file server expects paths relative to the root of the directory it's serving, and without stripping the prefix, it would look for files in a non-existent `/app` subdirectory.

	// This makes sure that when a request comes in for `/healthz`, it gets routed to `handlerfunction`. The `handlerfunction` is defined below and simply responds with a 200 OK and the text "OK".
	// similarly, the other routes are registered to their respective handler functions. The `apiCfg` struct is passed to the handlers that need access to the database or shared state.
	sermux.HandleFunc("GET /api/healthz", handlerfunction)
	sermux.HandleFunc("GET /admin/metrics", apiCfg.numberofRequests)
	sermux.HandleFunc("POST /admin/reset", apiCfg.reset)
	// sermux.HandleFunc("POST /api/validate_chirp", jsonHandler) THIS IS NOT NEEDED NOW, chirp gets validated and cleaned in chirpsHandler in /api/chirps endpoint, so we don't need a separate endpoint for that.
	sermux.HandleFunc("POST /api/users", apiCfg.usersHandler) // this is the endpoint for creating a new user, it expects a JSON body with an "email" field.
	sermux.HandleFunc("POST /api/login", apiCfg.userLogin)
	sermux.HandleFunc("POST /api/chirps", apiCfg.chirpsHandler) // this is the endpoint for creating a new chirp, it expects a JSON body with a "body" field and a "user_id" field.

	sermux.HandleFunc("GET /api/chirps", apiCfg.getAllChirps)
	sermux.HandleFunc("GET /api/chirps/{chirpID}", apiCfg.getChirpByID)
	// 	Note: this line runs _after_ `s` was created, but that's fine in Go - `s.Handler` holds a _reference_ to `sermux`, not a snapshot. So even though you registered the route after building the server struct, the server will still see it because it's looking at the same `sermux` object in memory.

	// ```go
	// 	err := s.ListenAndServe()
	// ```

	// This is the line that actually starts the server - it blocks (pauses execution here) and listens for incoming TCP connections on port 8080,
	// routing each one through `sermux`. It only returns when the server stops, usually due to an error.

	// ```go
	// 	if err != nil{
	// 		log.Printf("Error occured")
	// 		return
	// 	}
	// 	return
	// }
	// ```

	// If `ListenAndServe` returns an error (e.g., the port is already in use), you log a message and exit `main`.
	// The final `return` at the bottom is actually unreachable in the sense that `ListenAndServe` almost never returns `nil` - it blocks forever until something goes wrong.

	err1 := s.ListenAndServe()
	if err1 != nil {
		log.Printf("Error occured")
		return
	}
	// there was a return here that never got executed because ListenAndServe blocks until an error occurs, so the program would exit after logging the error.
}

// http.ResponseWriter is an interface that allows you to construct an HTTP response. It has methods for setting headers, writing the status code, and writing the body of the response.
// http.Request is a struct that represents an incoming HTTP request. It contains information like the method (GET, POST, etc.), URL, headers, and body of the request.
// http.Request is used as a pointer because it can be large and you want to avoid copying it around. Passing a pointer allows the handler to read from the request
// without making a full copy of it, which is more efficient.
func handlerfunction(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(200)
	w.Write([]byte("OK"))
}

func (cfg *apiConfig) middlewareMetricsInc(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cfg.fileserverHits.Add(1)
		next.ServeHTTP(w, r)
	})
}

func (cfg *apiConfig) numberofRequests(w http.ResponseWriter, r *http.Request) {
	x := cfg.fileserverHits.Load()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, fmt.Sprintf(`<html>
  <body>
    <h1>Welcome, Chirpy Admin</h1>
    <p>Chirpy has been visited %d times!</p>
  </body>
</html>
	
	`, x))
}

func (cfg *apiConfig) reset(w http.ResponseWriter, r *http.Request) {
	cfg.fileserverHits.Store(0)

	//Adding fucntionality to reset users in database as well

	if cfg.platform == "dev" {
		cfg.databasequeries.ResetUsers(r.Context())
		w.WriteHeader(200)
		w.Write([]byte("Counter reset successfully along with resetting users in database"))
	} else {
		w.WriteHeader(403)
		w.Write([]byte("Resetting users is only allowed in dev environment"))
	}

}

// WE DO NOT NEED THIS
// func jsonHandler(w http.ResponseWriter, r *http.Request) {

// 	type Body struct {
// 		JSONBODY string `json:"body"`
// 	}
// 	body := Body{}
// 	decoder := json.NewDecoder(r.Body)
// 	err := decoder.Decode(&body)

// 	if err != nil {
// 		respondWithError(w, http.StatusBadRequest, "Something went wrong")
// 	} else if len(body.JSONBODY) > 140 {
// 		respondWithError(w, http.StatusBadRequest, "Chirp is too long")

// 	} else {
// 		cleanString := cleanstringFunc(body.JSONBODY)

// 		respondWithJSON(w, 200, map[string]interface{}{"cleaned_body": cleanString})
// 	}

// }

func respondWithError(w http.ResponseWriter, code int, msg string) {

	type returnError struct {
		ERROR string `json:"error"`
	}
	returnVal := returnError{
		ERROR: msg,
	}

	w.Header().Set("Content-Type", "application/json")
	data, err := json.Marshal(returnVal)
	if err != nil {
		http.Error(w, "Error generating JSON response", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(code)
	w.Write(data)
}

func respondWithJSON(w http.ResponseWriter, code int, payload interface{}) {

	w.Header().Set("Content-Type", "application/json")
	data, err := json.Marshal(payload)
	if err != nil {
		http.Error(w, "Error generating JSON response", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(code)
	w.Write(data)

}

func cleanstringFunc(input string) string {
	// Remove leading and trailing whitespace

	Split := strings.Split(input, " ")

	for i, word := range Split {
		// Remove punctuation from each word

		if strings.ToLower(word) == "kerfuffle" || strings.ToLower(word) == "sharbert" || strings.ToLower(word) == "fornax" {
			Split[i] = "****"
		}
	}

	// Replace multiple spaces with a single space

	return strings.Join(Split, " ")

}

func (cfg *apiConfig) usersHandler(w http.ResponseWriter, r *http.Request) {

	type CreateUserParams struct {
		EMAIL    string `json:"email"`
		PASSWORD string `json:"password"`
	}
	body := CreateUserParams{}
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&body)
	log.Printf("decoded email: %q", body.EMAIL)
	log.Printf("decoded password: %q", body.PASSWORD)
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Something went wrong")
		return
	}
	hashedPassword, err1 := auth.HashPassword(body.PASSWORD)
	body.PASSWORD = hashedPassword
	if err1 != nil {
		log.Printf("hashPassword error: %v", err1)
		respondWithError(w, http.StatusInternalServerError, "Error hashing password")
		return
	}

	arg := database.CreateUserParams{
		Email:          body.EMAIL,
		HashedPassword: body.PASSWORD,
	}
	user, err2 := cfg.databasequeries.CreateUser(r.Context(), arg)
	if err2 != nil {
		log.Printf("createUser error: %v", err2)
		respondWithError(w, http.StatusInternalServerError, "Error creating user")
		return
	}
	// to have the expected json response containing id, created_at, updated_at, and email fields, we need to create a new struct
	// that contains only those fields and return it as the response.
	// This is because the User struct returned by CreateUser may contain additional fields that we don't want to expose in the API response and the
	// field names may be different from what we want to return in the API response.
	returnstruct := User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	}
	respondWithJSON(w, 201, returnstruct)
}

func (cfg *apiConfig) userLogin(w http.ResponseWriter, r *http.Request) {
	type loginParams struct {
		EMAIL    string `json:"email"`
		PASSWORD string `json:"password"`
	}
	body := loginParams{}
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&body)
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Couldn't decode login request json")
		return
	}

	user, err := cfg.databasequeries.GetUserByEmail(r.Context(), body.EMAIL)
	if err != nil {
		respondWithError(w, http.StatusNotFound, "User not found")
		return
	}

	userexist, err1 := auth.CheckPasswordHash(user.HashedPassword, body.PASSWORD)
	if err1 != nil {
		respondWithError(w, http.StatusInternalServerError, "Error checking password")
		return
	}
	if !userexist {
		respondWithError(w, 401, "Unauthorized")
		return
	}
	responseStruct := User{
		ID:        user.ID,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		Email:     user.Email,
	}

	respondWithJSON(w, 200, responseStruct)
}
func (cfg *apiConfig) chirpsHandler(w http.ResponseWriter, r *http.Request) {

	type CreateChirpParams struct {
		Body   string        `json:"body"`
		UserID uuid.NullUUID `json:"user_id"`
	}
	body := CreateChirpParams{}
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&body)

	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Something went wrong decoding json")
	} else if len(body.Body) > 140 {
		respondWithError(w, http.StatusBadRequest, "Chirp is too long")

	} else {
		body.Body = cleanstringFunc(body.Body)

		arg := database.CreateChirpParams{
			Body:   body.Body,
			UserID: body.UserID,
		}

		chirp, err2 := cfg.databasequeries.CreateChirp(r.Context(), arg)
		if err2 != nil {
			respondWithError(w, http.StatusBadRequest, "create chirp query failed")
		}
		returnstruct := Chirp{
			ID:        chirp.ID,
			CreatedAt: chirp.CreatedAt,
			UpdatedAt: chirp.UpdatedAt,
			Body:      chirp.Body,
			User_ID:   chirp.UserID.UUID,
		}

		respondWithJSON(w, 201, returnstruct)
	}
}

func (cfg *apiConfig) getAllChirps(w http.ResponseWriter, r *http.Request) {
	chirps, err := cfg.databasequeries.GetAllChirps(r.Context())
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Error fetching chirps")
		return
	}

	var response []Chirp
	for _, chirp := range chirps {
		response = append(response, Chirp{
			ID:        chirp.ID,
			CreatedAt: chirp.CreatedAt,
			UpdatedAt: chirp.UpdatedAt,
			Body:      chirp.Body,
			User_ID:   chirp.UserID.UUID,
		})
	}

	respondWithJSON(w, 200, response)

}

func (cfg *apiConfig) getChirpByID(w http.ResponseWriter, r *http.Request) {
	chirpID := r.PathValue("chirpID")
	parsedID, err := uuid.Parse(chirpID)
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Invalid chirp ID")
		return
	}
	chirp, err := cfg.databasequeries.GetChirpByID(r.Context(), parsedID)
	if err != nil {
		respondWithError(w, http.StatusNotFound, "Chirp not found")
		return
	}

	respondWithJSON(w, 200, Chirp{
		ID:        chirp.ID,
		CreatedAt: chirp.CreatedAt,
		UpdatedAt: chirp.UpdatedAt,
		Body:      chirp.Body,
		User_ID:   chirp.UserID.UUID,
	})
}
